# Funding options for Uni AI SDK
# Open source, community-driven project

# GitHub Sponsors
github: # Add your GitHub username if you set up sponsors

# Open Collective
# open_collective: uni-ai

# Custom
custom: https://uni-ai.dev/sponsor
